Update appdata files tags
gtkwave/gtkwave pull request #142
Opened 2022-08-04 04:58 UTC by aklsh

- Done as part of flatpak packaging
- Updated existing fields, and added new ones according to [Freedesktop AppStream specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent)

2022-08-04 14:48 UTC, rfuest commented
Concerning the application ID: This PR uses `net.sourceforge.GTKWave` as the application ID, but the GSettings schema and macOS plist use `com.geda.gtkwave`. `com.geda.gtkwave` is a bad ID according to the flatpak guidelines (https://docs.flatpak.org/en/latest/conventions.html#application-ids), because `geda.com` isn't related to GTKWave or the gEDA project. The GTK4 port will use the application ID in more places than the current version, so it would be good if we could agree on one ID.

These are the candidates IMO:
* `net.sourceforge.GTKWave`
* `io.github.GTKWave`
  If the project is supposed to move from SF to GitHub.
* `org.geda_project.GTKWave`
  I'm not sure of the status of the gEDA project and the relationship between GTKWave and gEDA.

2022-08-04 15:04 UTC, gtkwave commented
I'd say use github.  Eventually, I'll update the sourceforge site such that it will state that it exists only for historical reasons (e.g., if it's referenced in a paper or technical literature, etc.).
-Tony


    On Thursday, August 4, 2022, 10:48:15 AM EDT, Ralf Fuest ***@***.***> wrote:  
 
 


Concerning the application ID: This PR uses net.sourceforge.GTKWave as the application ID, but the GSettings schema and macOS plist use com.geda.gtkwave. com.geda.gtkwave is a bad ID according to the flatpak guidelines (https://docs.flatpak.org/en/latest/conventions.html#application-ids), because geda.com isn't related to GTKWave or the gEDA project. The GTK4 port will use the application ID in more places than the current version, so it would be good if we could agree on one ID.

These are the candidates IMO:
   
   - net.sourceforge.GTKWave
   - io.github.GTKWave   
If the project is supposed to move from SF to GitHub.
   - org.geda_project.GTKWave   
I'm not sure of the status of the gEDA project and the relationship between GTKWave and gEDA.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2022-08-04 16:19 UTC, rfuest commented
Sounds good to me. But we might want to use `io.github.gtkwave.GTKWave`, which is suggested in the link I mentioned earlier. The `io.github.gtkwave` namespace could then also be used for other apps, e.g. `io.github.gtkwave.rtlbrowse`.

2022-08-04 16:33 UTC, gtkwave commented
That sounds good to me.  

-Tony


    On Thursday, August 4, 2022, 12:19:20 PM EDT, Ralf Fuest ***@***.***> wrote:  
 
 


Sounds good to me. But we might want to use io.github.gtkwave.GTKWave, which is suggested in the link I mentioned earlier. The io.github.gtkwave namespace could then also be used for other apps, e.g. io.github.gtkwave.rtlbrowse.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

2022-08-05 02:00 UTC, aklsh commented
Changed to `io.github.gtkwave.GTKWave`

2022-08-06 01:10 UTC, rfuest commented
The appdata file looks good for version 3.3.111.

But why is GTKWave on Flathub built from a recent GIT version and not the 3.3.111 tarball? This causes a mismatch between the version shown in GTKWave and the appdata shown on Flathub (Version 3.4.0 vs. 3.3.111). And there is no description of the 3.4.0 changes in the appdata.

2022-08-06 03:02 UTC, aklsh commented
Oops. I didn't know there was a 3.4.0 release. I thought 3.3.111 was the latest and used that. I've fixed it by using a 3.3.111 tarball instead. Should be able to see it in a few hours after flathub signs and uploads it.

2022-08-06 18:10 UTC, rfuest requested changes
I did try the Flatpak version of GTKWave and it is mostly working as expected.

Except from a few nitpicks about the appdata I noticed two issues with the Flatpak version:
* I couldn't run the transaction example because of mismatched GLIBC versions.
  My host GLIBC is newer than the version in the GNOME 42 runtime, which caused the `transaction` executable to fail. I'm not sure what the best solution for this problem is, because it also extends to any other libraries which are used by a transaction filter executable that aren't available inside the sandbox. There are methods to execute commands on the host by using `flatpak-spawn` or a D-Bus interface, but that would require code changes and adding additional permissions. Compiling the filter as a static executable did also fix the problem in my case. At the moment I would suggest to just except this issue as a known limitation of the Flatpak version.
* Printing doesn't work correctly.
  Only printing to a file is available in the Flatpak version. Adding `socket=cups` with Flatseal fixed this issue. So this should probably be added to the YAML file.

2022-08-06 18:10 UTC, rfuest commented on gtkwave3-gtk3/share/appdata/gtkwave.appdata.xml
> +      <caption/>
The `caption` tag is optional.
```suggestion
```

2022-08-06 18:10 UTC, rfuest commented on gtkwave3-gtk3/share/appdata/gtkwave.appdata.xml
> +        <p>Skip over decimal point in timescale in viewer.</p>
Other projects on Flathub use a list for the changelog, which looks better IMO:
```suggestion
        <ul>
            <li>Rendering fix for filled rectangles and line caps in Cairo.</li>
            <li>Fix in fstapi for read start limit time.</li>
            <li>Use GtkSearchEntry in SST.</li>
            <li>Convert entrybox to use dialog box.</li>
            <li>Entrybox: use default response instead of signal handler.</li>
            <li>Updated show-change widget.</li>
            <li>Fix xml2stems when begin blocks are in functions.</li>
            <li>Skip over decimal point in timescale in viewer.</li>
        </ul>
```

2022-08-06 18:10 UTC, rfuest commented on gtkwave3-gtk3/share/appdata/gtkwave.appdata.xml
> -<updatecontact>bybell@rocketmail.com</updatecontact>
Is there a reason why you removed the `updatecontact` tag from the appdata?

2022-08-07 02:24 UTC, aklsh commented on gtkwave3-gtk3/share/appdata/gtkwave.appdata.xml
> -<updatecontact>bybell@rocketmail.com</updatecontact>
Oh my bad. I was using my email for the update contact for the flatpak and removed it while putting it here.

2022-08-07 02:44 UTC, aklsh commented
> At the moment I would suggest to just except this issue as a known limitation of the Flatpak version.

Sure. I'll mention it in the flatpak description.

> Only printing to a file is available in the Flatpak version. Adding `socket=cups` with Flatseal fixed this issue. So this should probably be added to the YAML file.

Done.

2022-08-07 14:26 UTC, rfuest commented
One final thing: Could you also update the other two appdata files to the latest version? I would fix this myself, but I don't have the required permissions to push to your branch.

I've tested the latest version on Flathub and printing works now. It's great to see that GTKWave is now also available as Flatpak.

2022-08-07 16:57 UTC, rfuest approved these changes

2022-08-07 16:57 UTC, merged